### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by sinemacula** [mmghv/lumen-route-binding#13]
Any chance we can add support for Laravel/Lumen 8.x?

I can't see any breaking changes in Lumen 8 so assume it should be as simple as just updating the package dependencies...

**Comment by jasurbek97** [comment]
lumen 8.x please !

**Comment by mmghv** [comment]
Updated the dependencies to support Lumen 8, you can now use the [latest version](https://github.com/mmghv/lumen-route-binding/releases/tag/1.5.2).
