### ISSUE TITLE
Support for Lumen 9.x

### ISSUE THREAD

**Issue by jorgemudry** [mmghv/lumen-route-binding#17]
Hi @mmghv ! I know that a [PR](https://github.com/mmghv/lumen-route-binding/pull/16) was merged adding support to Lumen 9.x but it seems that no release was created.
When I try to require this package I get this error:

<img width="1422" alt="Screen Shot 2022-03-15 at 21 33 44" src="https://user-images.githubusercontent.com/1508989/158494169-779ccf0b-d277-40df-9ee8-ae21cc1016e5.png">

Thanks in advance!

Jorge

**Comment by mmghv** [comment]
Sorry forgot to release it, you should be able to install it now.
