### ISSUE TITLE
Class 'app/Providers/RouteBindingServiceProvider' not found

### ISSUE THREAD

**Issue by MohanadI** [mmghv/lumen-route-binding#2]
Hello , 

I create RouteBindingServiceProvider.php in app/Providers and then I register the provider in the app.php 
but still gives me this error 

`Class 'app/Providers/RouteBindingServiceProvider' not found`

**Comment by mmghv** [comment]
Did you probably NameSpace your provider?
What's the content of the file?
and what version of Lumen you're using?

**Comment by MohanadI** [comment]
Yes 
```
<?php
namespace App\Providers;

use mmghv\LumenRouteBinding\RouteBindingServiceProvider as BaseServiceProvider;

class RouteBindingServiceProvider extends BaseServiceProvider
{
    /**
     * Boot the service provider
     */
    public function boot()
    {
        // The binder instance
        $binder = $this->binder;

        // Here we define our bindings
    }
}
```

I am using 5.4

**Comment by mmghv** [comment]
Did you happen to change your application namespace?

If no try to replicate the problem on a fresh installation of Lumen and provide the steps to replicate the problem.

**Comment by mmghv** [comment]
Oh I see what's wrong .. I'm sorry it's my fault it's a typo in the documentation ..
To register the service provider, replace this line in `bootstrap/app.php` :

```PHP
$app->register('app/Providers/RouteBindingServiceProvider');
```

With this one :

```PHP
$app->register('App\Providers\RouteBindingServiceProvider');
```

Notice the capital `A` in `App` and the `\` instead of `/`
I'll fix it in the doc, Thanks for reporting :)

**Comment by MohanadI** [comment]
perfect , thank you.
