### ISSUE TITLE
Undefined variable: binder

### ISSUE THREAD

**Issue by MohanadI** [mmghv/lumen-route-binding#3]
Undefined variable: binder in web.php (  routes file )

**Comment by mmghv** [comment]
You shouldn't define the bindings in the routes file, you should define them in the service provider you added in `app/Providers` in the boot method, see the [docs](https://github.com/mmghv/lumen-route-binding/#where-to-define-our-bindings) for more details.

Though you still can define them in the routes file but you need to get the binder instance from the IoC container like this :

```PHP
// Get the $binder instance from the IoC Container
$binder = $app['bindingResolver'];

// Then define your bindings here ..
```
