### ISSUE TITLE
Lumen 5.5 Support

### ISSUE THREAD

**Issue by awjudd** [mmghv/lumen-route-binding#5]
I recently updated my website to Lumen 5.5 and didn't realize that this did not support it.  Luckily, the only change which appears to be necessary is [here](https://github.com/mmghv/lumen-route-binding/blob/master/src/RouteBindingServiceProvider.php#L63).

```php
foreach ($this->app->routes->getRoutes() as $route) {
```

I only just started to test this but that does make my application work again.

**Comment by mmghv** [comment]
Thanks for reporting.

Fixed in the new release `1.4.0`.

Update your package :
```
composer update
```
