### ISSUE TITLE
Access bound model in FormRequest

### ISSUE THREAD

**Issue by ilyaskhametov** [mmghv/lumen-route-binding#7]
**Stack:**
`laravel/lumen-framework: 5.6.*`, `mmghv/lumen-route-binding: ^1.0`

I integrated FormRequests into my project. Now I need to access bound model in one of my FormRequests, but don't know how to do it.

I have a route:
```php
$router->put('{user}', 'UserController@update');
```

And a controller method, where UpdateRequest is a subclass of a FormRequest:
```php
public function update(User $user, UpdateRequest $request): JsonResponse
{
    ...
}
```

Also, I have this line in `RouteBindingServiceProvider`:
```php
$binder->bind('user', \Core\Users\Entity\User::class);
```

So, the question is how to access/resolve already bound instance of a User model inside UpdateRequest, which has this contents:
```php
class UpdateRequest extends FormRequest
{
    public function rules()
    {
        // Need to access bound model here
    }
}
```

**Comment by mmghv** [comment]
Did you try `$this->route('user')` ?

According to [Laravel Form Requests docs](https://laravel.com/docs/5.8/validation#form-request-validation) you can access route URI parameters using the `route` method in Form Requests :

> Also note the call to the `route` method in the example above. This method grants you access to the URI parameters defined on the route being called.

**Comment by ilyaskhametov** [comment]
This will return me a value passed in `{id}` parameter, won't it? What I need is to get a User instance bound with the help of **route binding** provided by your package. I want to access it like I access it in controller bound to request.
