### ISSUE TITLE
Route binding always run before middleware

### ISSUE THREAD

**Issue by sornss** [mmghv/lumen-route-binding#9]
First, thanks for your package. I have tried it with complete setup of dusterio/lumen-passport to protect some private endpoints using the auth middleware as you can see in the routes down below.

**RouteBindingServiceProvider** // Use a custom method on **ArticleRepository** class
`
<pre>
...
$binder->implicitBind('App\Repositories', '', 'Repository', 'findForRoute');
...
</pre>
`

**ArticleRepository class**
`
<pre>
...
public function findForRoute($val)
{
            return $this->articleModel->where('slug', $val)->firstOrFail();
}
...
</pre>
`

**routes**
`
<pre>
...
$router->group(['middleware' => ['auth'], 'prefix' => 'articles'], function () use ($router) {
            $router->get('/', 'ArticleController@index')->name('api.get.articles');
            $router->post('/', 'ArticleController@store')->name('api.post.article);
            $router->get('/{article}', 'ArticleController@show')->name('api.get.article');
            $router->put('/{article}', 'ArticleController@update')->name('api.put.article');
            $router->patch('/{article}', 'ArticleController@update')->name('api.patch.article');
            $router->delete('/{article}', 'ArticleController@destroy')->name('api.delete.article');
});
...
</pre>
`

While testing from Postman to the route 'api.get.article' **without a good bearer token** on the address http://myapi.com/articles/1 to get an article that does not exist, the reply weirdly throws ModelNotFound exception instead of Authentication exception from the middleware. Weirdly enough, with a good bearer token, I notice proper reply with an Authentication exception as unauthenticated.
I have double checked MySQL log while doing the test, it also shows the query executed related to the get request. It looks all routes binding to {article} affected the same issue.

With the existing issue, I really hate someone may check if a particular article or other important model exists just try the method with any random ID without authenticated. This could be a vulnerability/security, minor or major as it could affect the user of the framework.

I wish you or anyone could fix as soon as possible.

Thank you.

sornss

**Comment by mmghv** [comment]
This is an unfortunate limitation in Lumen, check out this [answer](https://github.com/mmghv/lumen-route-binding/issues/8#issuecomment-532649162)

I hate to say it but, it might be better for you if you drop `lumen-route-binding` all together and resolve the models yourself instead.

If you can workout any solution or workaround for this limitation that would be great. or maybe submit a request to `Lumen` to implement the `middlewarePriority` feature, I would do it if I have the time.

**Comment by sornss** [comment]
Sorry, my bad, did not check the closed issues.

Thank you
